spring:
  application:
    name: backend
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  mvc:
    static-path-pattern: /uploads/**
  web:
    resources:
      static-locations: file:./uploads/

app:
  upload-dir: uploads

# SpringDoc OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    enabled: true
  show-actuator: false
  default-produces-media-type: application/json
  packages-to-scan: com.kody.coinsec.backend.controller

# Sa-Token
sa-token:
  token-name: satoken
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: true

